[package]
name = "ribbon"
version = "0.1.0"
authors = ["Alice McKean <mckean.kylej@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
